# version: "3.9"
services:
  1hummingbot:
    container_name: 1_hummingbot
    # image: hummingbot/hummingbot:latest
    build: #Uncomment this and comment image if you want to build it locally
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
      # Add directories you need
      - /home/tyler/quant/API_call_tests:/home/tyler/hummingbot/API_call_tests
      - /home/tyler/hummingbot/data/KrakenData:/home/tyler/hummingbot/data/KrakenData
      - /home/tyler/hummingbot/qfl:/home/tyler/hummingbot/qfl
      - /home/tyler/hummingbot/data:/home/tyler/hummingbot/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host

  2hummingbot:
    container_name: 2_hummingbot
    # image: hummingbot/hummingbot:latest
    build: #Uncomment this and comment image if you want to build it locally
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
      # Add directories you need
      - /home/tyler/quant/API_call_tests:/home/tyler/hummingbot/API_call_tests
      - /home/tyler/hummingbot/data/KrakenData:/home/tyler/hummingbot/data/KrakenData
      - /home/tyler/hummingbot/qfl:/home/tyler/hummingbot/qfl
      - /home/tyler/hummingbot/data:/home/tyler/hummingbot/data

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host




  3hummingbot:
    container_name: 3_hummingbot
    # image: hummingbot/hummingbot:latest
    build: #Uncomment this and comment image if you want to build it locally
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs_2
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
      # Add directories you need
      - /home/tyler/quant/API_call_tests:/home/tyler/hummingbot/API_call_tests
      - /home/tyler/hummingbot/data/KrakenData:/home/tyler/hummingbot/data/KrakenData
      - /home/tyler/hummingbot/qfl:/home/tyler/hummingbot/qfl
      - /home/tyler/hummingbot/data:/home/tyler/hummingbot/data

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host




  4hummingbot:
    container_name: 4_hummingbot
    # image: hummingbot/hummingbot:latest
    build: #Uncomment this and comment image if you want to build it locally
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs_2
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
      # Add directories you need
      - /home/tyler/quant/API_call_tests:/home/tyler/hummingbot/API_call_tests
      - /home/tyler/hummingbot/data/KrakenData:/home/tyler/hummingbot/data/KrakenData
      - /home/tyler/hummingbot/qfl:/home/tyler/hummingbot/qfl
      - /home/tyler/hummingbot/data:/home/tyler/hummingbot/data

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host




    #  environment:
    #    - CONFIG_PASSWORD=a
    #    - CONFIG_FILE_NAME=simple_pmm_example.py
    #    - SCRIPT_CONFIG=conf_simple_pmm_example.yaml

  gateway:
   container_name: gateway
   image: hummingbot/gateway:latest
   ports:
     - "15888:15888"
     - "8080:8080"
   volumes:
     - "./gateway_files/conf:/home/gateway/conf"
     - "./gateway_files/logs:/home/gateway/logs"
     - "./gateway_files/db:/home/gateway/db"
     - "./certs:/home/gateway/certs"
  #  environment:
  #    - GATEWAY_PASSPHRASE=a
