# strategy_config.py
from decimal import Decimal

# Configuration parameters to be used for instantiating the bot
STRATEGY_CONFIG = {
    'PAXG_BTC': {
        'trading_pair': 'PAXG-BTC',
        'exchange': 'kraken',
        'base_asset': 'PAXG',
        'quote_asset': 'BTC',
        'history_market': 'PAXGXBT',
        'min_profitability': Decimal(0.015),
        'buy_p': Decimal(0.975),
        'sell_p': Decimal(1.025),
        'quote_order_amount': Decimal(0.0001),
        'order_amount': Decimal(0.002),
        'max_order_amount': Decimal(0.01),
        'maximum_orders': 50,
        'inv_target_percent': Decimal(0.50),
        'order_shape_factor': Decimal(2.0),
        'history_name': 'PAXGXBT_60.csv',
        'trade_history_name': 'trades_PAXG_BTC',
        'chart_period': '60',
        'volatility_periods': 168,
        'rolling_periods': 12,
        'trading_style': 'QFL', # 'Account Building' or 'QFL'
    },
    'XLM_EUR': {
        'trading_pair': 'XLM-EUR',
        'exchange': 'kraken',
        'base_asset': 'XLM',
        'quote_asset': 'EUR',
        'history_market': 'XXLMZEUR',
        'min_profitability': Decimal(0.015),
        'buy_p': Decimal(0.970),
        'sell_p': Decimal(1.030),
        'quote_order_amount': Decimal(3.5),
        'order_amount': Decimal(40),
        'max_order_amount': Decimal(500),
        'maximum_orders': 170,
        'inv_target_percent': Decimal(0.0),
        'order_shape_factor': Decimal(2.0),
        'history_name': 'XLMEUR_60.csv',
        'trade_history_name': 'trades_XLM',
        'chart_period': '60',
        'volatility_periods': 168,
        'rolling_periods': 12,
        'trading_style': 'QFL', # 'Account Building' or 'QFL'
    },
    'BSX_USD': {
        'trading_pair': 'BSX-USD',
        'exchange': 'kraken',
        'base_asset': 'BSX',
        'quote_asset': 'USD',
        'history_market': 'BSXUSD',
        'min_profitability': Decimal(0.015),
        'buy_p': Decimal(0.970),
        'sell_p': Decimal(1.030),
        'quote_order_amount': Decimal(5.0),
        'order_amount': Decimal(130000),
        'max_order_amount': Decimal(390000),
        'maximum_orders': 170,
        'inv_target_percent': Decimal(0.0),
        'order_shape_factor': Decimal(2.0),
        'history_name': 'BSXUSD_60.csv',
        'trade_history_name': 'trades_BSX_USD',
        'chart_period': '60',
        'volatility_periods': 168,
        'rolling_periods': 12,
        'trading_style': 'Account Building', # 'Account Building' or 'QFL'
    },
    'CPOOL_EUR': {
        'trading_pair': 'CPOOL-EUR',
        'exchange': 'kraken',
        'base_asset': 'CPOOL',
        'quote_asset': 'EUR',
        'history_market': 'CPOOLEUR',
        'min_profitability': Decimal(0.015),
        'buy_p': Decimal(0.970),
        'sell_p': Decimal(1.030),
        'quote_order_amount': Decimal(6.0),
        'order_amount': Decimal(33),
        'max_order_amount': Decimal(200),
        'maximum_orders': 170,
        'inv_target_percent': Decimal(0.0),
        'order_shape_factor': Decimal(2.0),
        'history_name': 'CPOOLEUR_60.csv',
        'trade_history_name': 'trades_CPOO',
        'chart_period': '60',
        'volatility_periods': 168,
        'rolling_periods': 12,
        'trading_style': 'Account Building', # 'Account Building' or 'QFL'
    },
}

